### ISSUE TITLE
SNAPSHOT artifacts are not deployed

### ISSUE THREAD

**Issue by MichaelF25** [fuinorg/event-store-maven-plugin#11]
Just saw that SNAPSHOT artifacts are not deployed to Sonatype OSS snapshot repository as stated in the README.

At least I could not find anything on https://oss.sonatype.org/content/repositories/snapshots/org/fuin/

**Comment by michael-schnell** [comment]
Automating the snapshot deployment is on my list, but havent't managed it yet. For now it's a manual procedd. Should be availble now. I also fixed the README because it contained the wrong tag ("repository" instead of "pluginRepository").
