### ISSUE TITLE
Plugin does not work with Maven 3.3.x

### ISSUE THREAD

**Issue by MichaelF25** [fuinorg/event-store-maven-plugin#13]
[ERROR] Failed to execute goal org.fuin.esmp:es-maven-plugin:0.3.1:download (default) on project verita-event-store-impl: Execution default of goal org.fuin.esmp:es-maven-plugin:0.3.1:download failed: A required class was missing while executing org.fuin.esmp:es-maven-plugin:0.3.1:download: org/slf4j/helpers/MarkerIgnoringBase
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.fuin.esmp:es-maven-plugin:0.3.1
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/mforstner/.m2/repository/org/fuin/esmp/es-maven-plugin/0.3.1/es-maven-plugin-0.3.1.jar
[ERROR] urls[1] = file:/Users/mforstner/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.20/plexus-utils-3.0.20.jar
[ERROR] urls[2] = file:/Users/mforstner/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
[ERROR] urls[3] = file:/Users/mforstner/.m2/repository/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar
[ERROR] urls[4] = file:/Users/mforstner/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.0.M1/org.eclipse.sisu.inject-0.3.0.M1.jar
[ERROR] urls[5] = file:/Users/mforstner/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[6] = file:/Users/mforstner/.m2/repository/org/apache/commons/commons-exec/1.3/commons-exec-1.3.jar
[ERROR] urls[7] = file:/Users/mforstner/.m2/repository/org/apache/commons/commons-compress/1.9/commons-compress-1.9.jar
[ERROR] urls[8] = file:/Users/mforstner/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar
[ERROR] urls[9] = file:/Users/mforstner/.m2/repository/org/fuin/utils4j/0.8.0/utils4j-0.8.0.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[project>de.cpg.oss.verita:verita-parent:2.0.0-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]
[ERROR] 
[ERROR] -----------------------------------------------------: org.slf4j.helpers.MarkerIgnoringBase

This seems to be a known problem:

https://issues.apache.org/jira/browse/MNG-5787

**Comment by michael-schnell** [comment]
Now fixed in Maven 3.3.9.
